responses = {
    "user_da_ton_tai": "User already exists",
    "email_da_duoc_dang_ky": "Email is already in use, please try another email",
    "email_chua_duoc_dang_ky": "Email is not registered, please enter your correct registered email",
    "mat_khau_khong_dung": "Password is wrong",
    "co_loi_xay_ra": "Some thing wrong , pls try again",
    "check_email_to_get_code": "Check email to get code ",
    "dang_ky_thanh_cong": "Sign Up Success",
    "dang_ky_that_bai": "Registration failed",
    "code_bi_qua_thoi_gian": "Code is expired",
    "dang_nhap_thanh_cong": "Logged in successfully",
    "sai_mat_khau": "Wrong password",
    "tai_khoan_chua_duoc_dang_ky": "Account is not registered",
    "cap_nhat_mat_khau_moi_thanh_cong": "New password updated successfully",
    "cap_nhat_trang_thai_don_hang_thanh_cong": "Update order status successfully",
    "sai_code": "Wrong code",
    "cam_on_dong_gop_cua_ban": "Thank you for your contribution",
    "sua_thong_tin_thanh_cong": "Information processing successfully",
    "phien_dang_nhap_het_han": "Login session expired",
    "da_them_san_pham_vao_gio_hang_thanh_cong": "Product added to cart successfully",
    "da_cap_nhat_so_luong_san_pham_trong_gio_hang_thanh_cong": "The number of products in the shopping cart has been successfully updated",
    "da_xoa_san_pham_khoi_gio_hang_thanh_cong": "Product successfully removed from cart",
    "du_lieu_yeu_cau_khong_hop_le": "Invalid request data",
    "khong_tim_thay_san_pham": "No products found",
    "xoa_tai_khoan_thanh_cong": "Account deleted successfully",
    "da_them_san_pham_thanh_cong": "Product added successfully",
    "ten_san_pham_da_ton_tai": "Product name already exists",
    "sua_thong_tin_san_pham_thanh_cong": "Successfully edited product information",
    "khong_tim_thay_id_san_pham_trung_khop": "No matching product id found",
    "tai_khoan_khong_co_quyen_nay": "Account does not have this permission",
    "khong_tim_thay_email_dang_ky_code": "Can't find the email with the signing code",
}
